[package]
name = "hello-world"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
impl-opaque = { workspace = true }
